// Database seed script
// Run with: node scripts/seed-db.mjs

const categoriesData = [
  {
    id: "marketing",
    nameEn: "Marketing & Brand",
    nameZh: "市场与品牌",
    descEn: "Skills for brand strategy, market intelligence, and marketing operations.",
    descZh: "品牌策略、市场情报和营销运营相关技能。",
    color: "#FF4500",
    icon: "/images/category-marketing.png",
    sortOrder: 1,
  },
  {
    id: "writing",
    nameEn: "Writing & Editing",
    nameZh: "写作与编辑",
    descEn: "Skills for content creation, technical writing, and format conversion.",
    descZh: "内容创作、技术写作和格式转换相关技能。",
    color: "#1E90FF",
    icon: "/images/category-writing.png",
    sortOrder: 2,
  },
  {
    id: "design",
    nameEn: "Design & Media",
    nameZh: "设计与多媒体",
    descEn: "Skills for UI engineering, visual assets, and media tools.",
    descZh: "界面工程、视觉资产和媒体工具相关技能。",
    color: "#9932CC",
    icon: "/images/category-design.png",
    sortOrder: 3,
  },
  {
    id: "coding",
    nameEn: "Coding & Engineering",
    nameZh: "编程与工程",
    descEn: "Skills for development workflow, cloud/DevOps, and security testing.",
    descZh: "开发流程、云原生和安全测试相关技能。",
    color: "#228B22",
    icon: "/images/category-coding.png",
    sortOrder: 4,
  },
  {
    id: "research",
    nameEn: "Research & Analysis",
    nameZh: "研究与分析",
    descEn: "Skills for data extraction, deep analysis, and domain-specific research.",
    descZh: "数据提取、深度分析和领域专用研究相关技能。",
    color: "#FF8C00",
    icon: "/images/hero-banner.png",
    sortOrder: 5,
  },
  {
    id: "productivity",
    nameEn: "Productivity & Tools",
    nameZh: "生产力与工具",
    descEn: "Skills for office suite, thinking and planning.",
    descZh: "办公套件、思维与规划相关技能。",
    color: "#708090",
    icon: "/images/hero-banner.png",
    sortOrder: 6,
  },
];

const skillsData = [
  // Marketing
  {
    id: "brand-guidelines",
    titleEn: "Brand Guidelines",
    titleZh: "品牌指南",
    descriptionEn: "Enforce Claude to follow preset corporate colors, fonts, and Tone of Voice.",
    descriptionZh: "强制 Claude 在生成内容时遵循预设的企业配色、字体和 Tone of Voice。",
    scenarioEn: "Generating PRD documents or press releases that meet CI standards.",
    scenarioZh: "生成符合 CI 标准的 PRD 文档或对外宣传稿。",
    category: "marketing",
    tagsEn: ["Brand & Strategy"],
    tagsZh: ["品牌策略"],
    source: "official",
    url: "https://github.com/anthropics/skills/tree/main/skills/brand-guidelines",
    sortOrder: 1,
  },
  {
    id: "brand-voice-analyzer",
    titleEn: "Brand Voice Analyzer",
    titleZh: "品牌声音分析器",
    descriptionEn: "Use Python scripts to quantify text tone, formality, and perspective.",
    descriptionZh: "使用 Python 脚本量化分析文本的语气、正式度和视角，确保"不讲 AI 味的废话"。",
    scenarioEn: "Auditing outsourced copy or AI-generated drafts.",
    scenarioZh: "审核外包文案或 AI 生成的初稿。",
    category: "marketing",
    tagsEn: ["Brand & Strategy"],
    tagsZh: ["品牌策略"],
    source: "community",
    author: "alirezarezvani",
    url: "https://github.com/alirezarezvani/claude-skills",
    sortOrder: 2,
  },
  {
    id: "domain-name-brainstormer",
    titleEn: "Domain Name Brainstormer",
    titleZh: "域名头脑风暴",
    descriptionEn: "Generate creative domain names and check availability for .com/.io/.ai.",
    descriptionZh: "生成创意域名并检查 .com/.io/.ai 等后缀的可用性。",
    scenarioEn: "Naming new products or side projects.",
    scenarioZh: "新产品/Side Project 命名构思。",
    category: "marketing",
    tagsEn: ["Brand & Strategy"],
    tagsZh: ["品牌策略"],
    source: "community",
    sortOrder: 3,
  },
  {
    id: "competitive-ads-extractor",
    titleEn: "Competitive Ads Extractor",
    titleZh: "竞品广告提取器",
    descriptionEn: "Scrape competitor copy from ad libraries, analyze hooks and value propositions.",
    descriptionZh: "从广告库抓取竞品文案、分析心理诱导点（Hooks）和价值主张。",
    scenarioEn: "Competitor analysis reports, finding differentiated selling points.",
    scenarioZh: "竞品分析报告，寻找差异化卖点。",
    category: "marketing",
    tagsEn: ["Market Intelligence"],
    tagsZh: ["市场情报"],
    source: "community",
    sortOrder: 4,
  },
  {
    id: "lead-research-assistant",
    titleEn: "Lead Research Assistant",
    titleZh: "潜客研究助手",
    descriptionEn: "Analyze product features, automate B2B lead search and generate outreach strategies.",
    descriptionZh: "分析产品特性，自动化搜索潜在 B2B 客户并生成 Outreach 策略。",
    scenarioEn: "Finding seed users during cold start.",
    scenarioZh: "冷启动阶段寻找种子用户。",
    category: "marketing",
    tagsEn: ["Market Intelligence"],
    tagsZh: ["市场情报"],
    source: "community",
    sortOrder: 5,
  },
  {
    id: "content-calendar-manager",
    titleEn: "Content Calendar Manager",
    titleZh: "内容日历管理器",
    descriptionEn: "Build content clusters and reuse chains (e.g., Blog -> Tweet), generate Notion/CSV calendars.",
    descriptionZh: "构建内容集群和复用链条（如 Blog -> Tweet），生成 Notion/CSV 格式日历。",
    scenarioEn: "Content marketing scheduling.",
    scenarioZh: "内容营销排期。",
    category: "marketing",
    tagsEn: ["Operations"],
    tagsZh: ["营销运营"],
    source: "community",
    sortOrder: 6,
  },
  {
    id: "raffle-winner-picker",
    titleEn: "Raffle Winner Picker",
    titleZh: "抽奖选择器",
    descriptionEn: "Fairly pick winners from a list using cryptographically secure algorithms.",
    descriptionZh: "使用加密安全算法从名单中公平抽取中奖者。",
    scenarioEn: "Community operations events.",
    scenarioZh: "社群运营活动。",
    category: "marketing",
    tagsEn: ["Operations"],
    tagsZh: ["营销运营"],
    source: "community",
    sortOrder: 7,
  },

  // Writing
  {
    id: "content-research-writer",
    titleEn: "Content Research Writer",
    titleZh: "内容研究写手",
    descriptionEn: "Execute a 6-stage workflow: Setup -> Outline -> Research -> Hook Optimization.",
    descriptionZh: "执行"环境设置->大纲->研究->钩子优化"的 6 阶段工作流，自动管理引用来源。",
    scenarioEn: "Writing in-depth industry analysis articles, white papers.",
    scenarioZh: "撰写深度行业分析文章、白皮书。",
    category: "writing",
    tagsEn: ["Content Creation"],
    tagsZh: ["内容创作"],
    source: "community",
    sortOrder: 1,
  },
  {
    id: "internal-comms",
    titleEn: "Internal Comms",
    titleZh: "内部沟通",
    descriptionEn: "Standardize internal communication documents (Weekly reports, FAQs, All-hands letters).",
    descriptionZh: "标准化内部沟通文档（周报、FAQ、全员信）。",
    scenarioEn: "Administrative announcements, project milestone syncs.",
    scenarioZh: "行政通告、项目里程碑同步。",
    category: "writing",
    tagsEn: ["Content Creation"],
    tagsZh: ["内容创作"],
    source: "official",
    url: "https://github.com/anthropics/skills/tree/main/skills/internal-comms",
    sortOrder: 2,
  },
  {
    id: "family-history-research",
    titleEn: "Family History Research",
    titleZh: "家族历史研究",
    descriptionEn: "Plan genealogy research strategies and resource lists.",
    descriptionZh: "规划家谱研究策略和资源清单。",
    scenarioEn: "Personal history research.",
    scenarioZh: "个人历史研究。",
    category: "writing",
    tagsEn: ["Content Creation"],
    tagsZh: ["内容创作"],
    source: "community",
    sortOrder: 3,
  },
  {
    id: "technical-writing-standards",
    titleEn: "Technical Writing Standards (7 Cs)",
    titleZh: "技术写作标准 (7C)",
    descriptionEn: "Enforce Clear, Concise principles, automatically remove 'anti-patterns' and vague words.",
    descriptionZh: "强制执行 Clear, Concise 等原则，自动移除"反模式"和模糊词汇。",
    scenarioEn: "Polishing API docs, technical white papers.",
    scenarioZh: "API 文档、技术白皮书润色。",
    category: "writing",
    tagsEn: ["Technical & Editing"],
    tagsZh: ["技术写作与编辑"],
    source: "community",
    sortOrder: 4,
  },
  {
    id: "changelog-generator",
    titleEn: "Changelog Generator",
    titleZh: "更新日志生成器",
    descriptionEn: "Automatically generate user-facing Release Notes from Git Commit history.",
    descriptionZh: "从 Git Commit 历史自动生成面向用户的 Release Notes。",
    scenarioEn: "Product version update announcements.",
    scenarioZh: "产品版本更新公告。",
    category: "writing",
    tagsEn: ["Technical & Editing"],
    tagsZh: ["技术写作与编辑"],
    source: "community",
    sortOrder: 5,
  },
  {
    id: "expert-editor",
    titleEn: "Expert Editor",
    titleZh: "专家编辑",
    descriptionEn: "Adopt a 'Critique -> Feedback -> Rewrite' loop instead of direct rewriting.",
    descriptionZh: "采用"批评->反馈->重写"的循环模式，而非直接重写，保留作者原意。",
    scenarioEn: "Refining important manuscripts.",
    scenarioZh: "精修重要文稿。",
    category: "writing",
    tagsEn: ["Technical & Editing"],
    tagsZh: ["技术写作与编辑"],
    source: "community",
    sortOrder: 6,
  },
  {
    id: "markdown-to-epub",
    titleEn: "Markdown to EPUB Converter",
    titleZh: "Markdown 转 EPUB 转换器",
    descriptionEn: "Convert MD documents into professionally formatted eBooks.",
    descriptionZh: "将 MD 文档转换为排版专业的电子书。",
    scenarioEn: "Publishing knowledge bases/blogs as books.",
    scenarioZh: "将知识库/博客集结成册发布。",
    category: "writing",
    tagsEn: ["Format Conversion"],
    tagsZh: ["格式转换"],
    source: "community",
    sortOrder: 7,
  },

  // Design
  {
    id: "frontend-design",
    titleEn: "Frontend Design",
    titleZh: "前端设计",
    descriptionEn: "Generate HTML/CSS/React code. Pro version injects specific aesthetics (Neumorphism, Minimalism).",
    descriptionZh: "生成 HTML/CSS/React 代码。Pro 版注入特定美学（如新拟态、极简主义）以抵抗"Bootstrap 风格"的平庸。",
    scenarioEn: "Quickly building Landing Pages or MVP prototypes.",
    scenarioZh: "快速搭建 Landing Page 或 MVP 原型。",
    category: "design",
    tagsEn: ["UI & Frontend"],
    tagsZh: ["界面工程"],
    source: "official",
    url: "https://github.com/anthropics/skills/tree/main/skills/frontend-design",
    sortOrder: 1,
  },
  {
    id: "web-asset-generator",
    titleEn: "Web Asset Generator",
    titleZh: "网页资产生成器",
    descriptionEn: "Automatically generate Favicons, Open Graph images, and validate dimensions.",
    descriptionZh: "自动生成 Favicon、Open Graph 图片，并校验尺寸。",
    scenarioEn: "Asset preparation before Web project launch.",
    scenarioZh: "Web 项目上线前的资产准备。",
    category: "design",
    tagsEn: ["UI & Frontend"],
    tagsZh: ["界面工程"],
    source: "community",
    url: "https://github.com/travisvn/awesome-claude-skills",
    sortOrder: 2,
  },
  {
    id: "canvas-design",
    titleEn: "Canvas Design",
    titleZh: "画布设计",
    descriptionEn: "Generate PNG/PDF designs (posters, flyers) based on aesthetic principles.",
    descriptionZh: "根据审美原则生成 PNG/PDF 设计稿（海报、传单）。",
    scenarioEn: "Event poster drafts, illustration generation.",
    scenarioZh: "活动海报初稿、配图生成。",
    category: "design",
    tagsEn: ["Visual Assets"],
    tagsZh: ["视觉资产"],
    source: "official",
    url: "https://github.com/anthropics/skills/tree/main/skills/canvas-design",
    sortOrder: 3,
  },
  {
    id: "algorithmic-art",
    titleEn: "Algorithmic Art",
    titleZh: "算法艺术",
    descriptionEn: "Generate programmatic/mathematical art graphics using p5.js.",
    descriptionZh: "使用 p5.js 生成程序化/数学艺术图形。",
    scenarioEn: "Generating unique background textures, data art.",
    scenarioZh: "生成独特的背景纹理、数据艺术。",
    category: "design",
    tagsEn: ["Visual Assets"],
    tagsZh: ["视觉资产"],
    source: "community",
    url: "https://github.com/anthropics/skills/tree/main/skills/algorithmic-art",
    sortOrder: 4,
  },
  {
    id: "image-enhancer",
    titleEn: "Image Enhancer",
    titleZh: "图像增强器",
    descriptionEn: "Improve clarity and sharpness of screenshots or low-quality images.",
    descriptionZh: "提升截图或低质图片的清晰度与锐度。",
    scenarioEn: "Optimizing software screenshots in documents.",
    scenarioZh: "优化文档中的软件截图。",
    category: "design",
    tagsEn: ["Visual Assets"],
    tagsZh: ["视觉资产"],
    source: "community",
    sortOrder: 5,
  },
  {
    id: "slack-gif-creator",
    titleEn: "Slack GIF Creator",
    titleZh: "Slack GIF 创建器",
    descriptionEn: "Generate GIFs that meet Slack size limits.",
    descriptionZh: "生成符合 Slack 尺寸限制的 GIF 动图。",
    scenarioEn: "Team atmosphere building, demo presentations.",
    scenarioZh: "团队氛围建设、演示 Demo。",
    category: "design",
    tagsEn: ["Media Tools"],
    tagsZh: ["媒体工具"],
    source: "community",
    url: "https://github.com/anthropics/skills/tree/main/skills/slack-gif-creator",
    sortOrder: 6,
  },
  {
    id: "video-downloader",
    titleEn: "Video Downloader",
    titleZh: "视频下载器",
    descriptionEn: "Download video footage from platforms like YouTube.",
    descriptionZh: "从 YouTube 等平台下载视频素材。",
    scenarioEn: "Competitor video footage archiving.",
    scenarioZh: "竞品视频素材存档。",
    category: "design",
    tagsEn: ["Media Tools"],
    tagsZh: ["媒体工具"],
    source: "community",
    sortOrder: 7,
  },

  // Coding
  {
    id: "superpowers-core-skills",
    titleEn: "Superpowers Core Skills",
    titleZh: "超能力核心技能",
    descriptionEn: "Includes 20+ skills like TDD, debugging, code review, autonomous sub-agent execution.",
    descriptionZh: "包含 TDD、调试、代码审查、自主子代理执行等 20+ 技能。",
    scenarioEn: "Complex full-stack development tasks.",
    scenarioZh: "复杂的全栈开发任务。",
    category: "coding",
    tagsEn: ["Dev Workflow"],
    tagsZh: ["开发流"],
    source: "community",
    url: "https://github.com/obra/superpowers",
    sortOrder: 1,
  },
  {
    id: "skill-creator",
    titleEn: "Skill Creator",
    titleZh: "技能创建器",
    descriptionEn: "Automatically write compliant SKILL.md files from natural language descriptions.",
    descriptionZh: "根据自然语言描述自动编写符合规范的 SKILL.md 文件。",
    scenarioEn: "Quickly extending Claude's skill library.",
    scenarioZh: "快速扩展 Claude 的技能库。",
    category: "coding",
    tagsEn: ["Dev Workflow"],
    tagsZh: ["开发流"],
    source: "community",
    url: "https://github.com/anthropics/skills/tree/main/skills/skill-creator",
    sortOrder: 2,
  },
  {
    id: "skill-seekers",
    titleEn: "Skill Seekers",
    titleZh: "技能探索者",
    descriptionEn: "Input doc URL, automatically learn and generate corresponding Claude Skill.",
    descriptionZh: "输入文档 URL，自动学习并生成对应的 Claude Skill。",
    scenarioEn: "Letting Claude quickly master internal frameworks or new libraries.",
    scenarioZh: "让 Claude 快速掌握公司内部框架或新出的库。",
    category: "coding",
    tagsEn: ["Dev Workflow"],
    tagsZh: ["开发流"],
    source: "community",
    sortOrder: 3,
  },
  {
    id: "anthropic-aws-skills-pack",
    titleEn: "Anthropic AWS Skills Pack",
    titleZh: "Anthropic AWS 技能包",
    descriptionEn: "Integrate AWS CDK, cost optimization, Bedrock Agent development.",
    descriptionZh: "集成 AWS CDK、成本优化、Bedrock Agent 开发。",
    scenarioEn: "Cloud architecture design, cost monitoring.",
    scenarioZh: "云架构设计、成本监控。",
    category: "coding",
    tagsEn: ["Cloud & DevOps"],
    tagsZh: ["云原生"],
    source: "community",
    sortOrder: 4,
  },
  {
    id: "ios-simulator-skill",
    titleEn: "iOS Simulator Skill",
    titleZh: "iOS 模拟器技能",
    descriptionEn: "Let Claude control iOS Simulator for automated operations and testing.",
    descriptionZh: "让 Claude 控制 iOS 模拟器进行自动化操作和测试。",
    scenarioEn: "Mobile App development and testing.",
    scenarioZh: "移动端 App 开发与测试。",
    category: "coding",
    tagsEn: ["Cloud & DevOps"],
    tagsZh: ["云原生"],
    source: "community",
    url: "https://github.com/travisvn/awesome-claude-skills",
    sortOrder: 5,
  },
  {
    id: "ffuf-web-fuzzing",
    titleEn: "FFUF Web Fuzzing",
    titleZh: "FFUF Web 模糊测试",
    descriptionEn: "Integrate FFUF tool for Web fuzzing (directory busting, parameter analysis).",
    descriptionZh: "集成 FFUF 工具进行 Web 模糊测试（目录爆破、参数分析）。",
    scenarioEn: "Security penetration testing, vulnerability scanning.",
    scenarioZh: "安全渗透测试、漏洞扫描。",
    category: "coding",
    tagsEn: ["Security & Testing"],
    tagsZh: ["安全与测试"],
    source: "community",
    url: "https://github.com/travisvn/awesome-claude-skills",
    sortOrder: 6,
  },
  {
    id: "webapp-testing",
    titleEn: "Webapp Testing (Playwright)",
    titleZh: "Web 应用测试 (Playwright)",
    descriptionEn: "Automatically write and execute browser end-to-end tests.",
    descriptionZh: "自动编写并执行浏览器端到端测试。",
    scenarioEn: "QA regression testing.",
    scenarioZh: "QA 回归测试。",
    category: "coding",
    tagsEn: ["Security & Testing"],
    tagsZh: ["安全与测试"],
    source: "community",
    url: "https://github.com/anthropics/skills/tree/main/skills/webapp-testing",
    sortOrder: 7,
  },
  {
    id: "d3-visualization",
    titleEn: "D3.js Visualization",
    titleZh: "D3.js 可视化",
    descriptionEn: "Generate interactive data visualization code.",
    descriptionZh: "生成交互式数据可视化代码。",
    scenarioEn: "Data Dashboard development.",
    scenarioZh: "数据 Dashboard 开发。",
    category: "coding",
    tagsEn: ["Security & Testing"],
    tagsZh: ["安全与测试"],
    source: "community",
    url: "https://github.com/travisvn/awesome-claude-skills",
    sortOrder: 8,
  },

  // Research
  {
    id: "article-extractor",
    titleEn: "Article Extractor",
    titleZh: "文章提取器",
    descriptionEn: "Extract web body text, metadata, remove ad interference.",
    descriptionZh: "提取网页正文、元数据，去除广告干扰。",
    scenarioEn: "Cleaning before saving webpages to Obsidian/RAG database.",
    scenarioZh: "将网页存入 Obsidian/RAG 数据库前的清洗。",
    category: "research",
    tagsEn: ["Extraction"],
    tagsZh: ["数据提取"],
    source: "community",
    sortOrder: 1,
  },
  {
    id: "youtube-transcript",
    titleEn: "YouTube Transcript",
    titleZh: "YouTube 字幕提取",
    descriptionEn: "Get video subtitles and generate summaries.",
    descriptionZh: "获取视频字幕并生成摘要。",
    scenarioEn: "Quickly digesting long video content.",
    scenarioZh: "快速消化长视频内容。",
    category: "research",
    tagsEn: ["Extraction"],
    tagsZh: ["数据提取"],
    source: "community",
    sortOrder: 2,
  },
  {
    id: "tapestry",
    titleEn: "Tapestry",
    titleZh: "知识织锦",
    descriptionEn: "Connect multiple docs, build knowledge graph and generate reviews.",
    descriptionZh: "串联多份文档，构建知识网络图谱并生成综述。",
    scenarioEn: "Literature review, multi-document comparative analysis.",
    scenarioZh: "文献综述、多文档对比分析。",
    category: "research",
    tagsEn: ["Analysis"],
    tagsZh: ["深度分析"],
    source: "community",
    sortOrder: 3,
  },
  {
    id: "meeting-insights-analyzer",
    titleEn: "Meeting Insights Analyzer",
    titleZh: "会议洞察分析器",
    descriptionEn: "Analyze meeting records for speaking ratios, communication patterns, and conflicts.",
    descriptionZh: "分析会议记录的发言比例、沟通模式和潜在冲突。",
    scenarioEn: "Team management review.",
    scenarioZh: "团队管理复盘。",
    category: "research",
    tagsEn: ["Analysis"],
    tagsZh: ["深度分析"],
    source: "community",
    sortOrder: 4,
  },
  {
    id: "claude-scientific-skills",
    titleEn: "Claude Scientific Skills",
    titleZh: "Claude 科研技能",
    descriptionEn: "Includes 125+ scientific skills like bioinformatics, chemistry, statistical plotting.",
    descriptionZh: "包含生物信息、化学、统计绘图等 125+ 科研技能。",
    scenarioEn: "Academic research, experimental data processing.",
    scenarioZh: "学术研究、实验数据处理。",
    category: "research",
    tagsEn: ["Domain Specific"],
    tagsZh: ["领域专用"],
    source: "community",
    url: "https://github.com/K-Dense-AI/claude-scientific-skills",
    sortOrder: 5,
  },

  // Productivity
  {
    id: "office-suite",
    titleEn: "Docx / PDF / XLSX / PPTX Manager",
    titleZh: "Office 文档管理器",
    descriptionEn: "Directly read, edit, and generate Office native files (non-text).",
    descriptionZh: "直接读取、编辑和生成 Office 原生文件（非纯文本）。",
    scenarioEn: "Generating Excel reports with formulas, formatted Word contracts, PPT decks.",
    scenarioZh: "生成带公式的 Excel 报表、排版好的 Word 合同、PPT 演示文稿。",
    category: "productivity",
    tagsEn: ["Office Suite"],
    tagsZh: ["办公套件"],
    source: "official",
    url: "https://github.com/anthropics/skills/tree/main/skills/docx",
    sortOrder: 1,
  },
  {
    id: "theme-factory",
    titleEn: "Theme Factory",
    titleZh: "主题工厂",
    descriptionEn: "One-click professional design themes for docs, slides, or web apps.",
    descriptionZh: "一键为文档、幻灯片或网页应用专业设计主题。",
    scenarioEn: "Beautifying rough internal documents.",
    scenarioZh: "美化粗糙的内部文档。",
    category: "productivity",
    tagsEn: ["Office Suite"],
    tagsZh: ["办公套件"],
    source: "community",
    url: "https://github.com/anthropics/skills/tree/main/skills/theme-factory",
    sortOrder: 2,
  },
  {
    id: "brainstorming",
    titleEn: "Brainstorming",
    titleZh: "头脑风暴",
    descriptionEn: "Guide vague ideas into mature schemes through structured questioning.",
    descriptionZh: "通过结构化提问引导，将模糊想法转化为成熟方案。",
    scenarioEn: "Product Feature ideation.",
    scenarioZh: "产品 Feature 构思。",
    category: "productivity",
    tagsEn: ["Thinking & Planning"],
    tagsZh: ["思维与规划"],
    source: "official",
    sortOrder: 3,
  },
  {
    id: "ship-learn-next",
    titleEn: "Ship-Learn-Next",
    titleZh: "交付-学习-迭代",
    descriptionEn: "Suggest next steps based on 'Deliver-Learn-Iterate' loop and feedback.",
    descriptionZh: "基于"交付-学习-迭代"循环，根据反馈建议下一步行动。",
    scenarioEn: "Agile Sprint planning, personal learning path adjustment.",
    scenarioZh: "敏捷开发 Sprint 规划、个人学习路径调整。",
    category: "productivity",
    tagsEn: ["Thinking & Planning"],
    tagsZh: ["思维与规划"],
    source: "community",
    sortOrder: 4,
  },
  {
    id: "writing-plans",
    titleEn: "Writing Plans",
    titleZh: "写作计划",
    descriptionEn: "Enforce detailed implementation plans (Bite-sized steps) before execution.",
    descriptionZh: "强制在执行前生成详细实施计划（Bite-sized steps）。",
    scenarioEn: "Reducing resistance to complex tasks.",
    scenarioZh: "降低复杂任务的执行阻力。",
    category: "productivity",
    tagsEn: ["Thinking & Planning"],
    tagsZh: ["思维与规划"],
    source: "community",
    sortOrder: 5,
  },
];

// Output JSON for seeding
console.log(JSON.stringify({ categories: categoriesData, skills: skillsData }, null, 2));
